use clap::Parser;

mod lib;

/// Program to generate repots based on timesheets generated by timesheet-generator.
#[derive(Parser, Debug)]
#[command(author, version, about, long_about = None)]
struct Opts {
    /// path to file to read
    #[arg(short, long)]
    input: Option<String>
}

fn main() {
    let opts: Opts = Opts::parse();
    match lib::generate_report(opts.input.as_deref()) {
        Ok(report) => {
            for line in report {
                println!("{:?}", line);
            }
        }
        Err(err) => match err {
            lib::TimesheetParseError::IOError(_) => todo!(),
            lib::TimesheetParseError::CSVError(_) => todo!(),
            lib::TimesheetParseError::DateError(_) => todo!(),
        }
    }
}
